blueprint:
  name: "AWTRIX MQTT Discovered Apps Dropdown"
  description: >
    Discover apps from a selected AWTRIX device via MQTT and update an input_select dropdown.
  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: "Select the AWTRIX light"
      selector:
        device:
          filter:
            integration: mqtt
            manufacturer: Blueforcer
            model: AWTRIX 3
          multiple: false
    input_select_target:
      name: Input Select
      description: "Dropdown entity for discovered apps"
      selector:
        entity:
          domain: input_select

mode: restart

trigger:
  - platform: mqtt
    topic: "{{ device_entities(awtrix) | map('entity_id') | first | regex_replace('^sensor\\.|\\.state$', '') }}/custom/#"

variables:
  new_app: "{{ trigger.topic.split('/')[-1] }}"
  existing_apps: "{{ state_attr(this.entity_id, 'apps') | default([]) }}"
  updated_apps: "{{ (existing_apps + [new_app]) | unique | sort }}"

action:
  - service: input_select.set_options
    target:
      entity_id: !input input_select_target
    data:
      options: "{{ updated_apps }}"
