- alias: Awtrix Effekte
  trigger:
    - platform: time_pattern
      minutes: "/5"
  action:
    - service: mqtt.publish
      data:
        qos: 2
        retain: true
        payload: >-
          {
            "effect": "{{[ 'BrickBreaker', 'Checkerboard', 'Fireworks', 'PingPong', 'Radar', 'Ripple', 'Snake', 'TwinklingStars', 'TheaterChase', 'ColorWaves', 'SwirlOut', 'SwirlIn', 'LookingEyes', 'Matrix', 'Pacifica', 'Plasma', 'PlasmaCloud' ]|random }}",
            "rainbow": false,
            "duration": 10
          }
        topic: awtrix_a90760/custom/effects