blueprint:
  name: Awtrix Light Year Progress
  description: >-
    Displays the current year's progress as a percentage on an Awtrix Light device.
    The automation updates hourly.
  domain: automation
  source_url: https://community.home-assistant.io/t/awtrix-light-year-progress-blueprint/
  input:
    awtrix_device:
      name: Awtrix Light Device
      description: Select the Awtrix Light device to display the progress.
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
    icon:
      name: Icon ID
      description: >-
        The icon to display. Example: "813" for an hourglass. 
        Find icon IDs in your Awtrix Light device's web UI.
      default: "813"
      selector:
        text:
    app_name:
      name: Custom App Name
      description: The name for the custom app topic (e.g., yearprogress).
      default: "yearprogress"
      selector:
        text:

# This defines the automation that will be created from the blueprint.
trigger:
  - platform: time_pattern
    # Trigger every hour at the top of the hour.
    hours: "*"
    minutes: 0

variables:
  # Get the device name from the selected device input.
  device_name: !input awtrix_device
  # Get the custom app name from the input.
  app_name: !input app_name
  # Get the icon ID from the input.
  icon: !input icon

action:
  - service: mqtt.publish
    data:
      # Dynamically create the MQTT topic from the device and app names.
      topic: "{{ device_attr(device_name, 'name') | lower }}/custom/{{ app_name }}"
      payload: >-
        {# Get the start of the current year #}
        {%- set start_of_year = now().replace(month=1, day=1, hour=0, minute=0, second=0, microsecond=0) -%}
        {# Get the start of the next year for an accurate total #}
        {%- set start_of_next_year = start_of_year.replace(year=now().year + 1) -%}

        {# Calculate total seconds in the current year #}
        {%- set total_seconds = as_timestamp(start_of_next_year) - as_timestamp(start_of_year) -%}
        {# Calculate seconds passed since the start of the year #}
        {%- set elapsed_seconds = as_timestamp(now()) - as_timestamp(start_of_year) -%}
        
        {# Calculate the progress percentage and truncate to a whole number #}
        {%- set progress = ((elapsed_seconds / total_seconds) * 100) | int -%}

        {# Format the JSON payload for Awtrix Light #}
        {
          "text": "{{ progress }}%",
          "icon": "{{ icon }}"
        }
      qos: 0
      retain: false

mode: single